/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ca-central-1",
    "aws_cognito_identity_pool_id": "ca-central-1:0ef62857-9cc3-4433-b0b4-169bef371e98",
    "aws_cognito_region": "ca-central-1",
    "aws_user_pools_id": "ca-central-1_J6ltmilIz",
    "aws_user_pools_web_client_id": "2nc44d97o0gaucqm4jtsc5ovtp",
    "oauth": {}
};


export default awsmobile;
